"use client";

import { useMemo, useState } from "react";
import type { ReactNode } from "react";
import { projects } from "@/lib/demo-data";
import { ExportMenu } from "./ExportMenu";

const formatCdf=(value:number|null)=>value==null?"Non publié dans la source liée":`${new Intl.NumberFormat("fr-FR").format(value)} CDF`;
function ProgressLine({label,value,secondary=false}:{label:string;value:number|null;secondary?:boolean}){if(value==null)return <div className="progress-block progress-unavailable"><div><span>{label}</span><b>À documenter</b></div><p>Aucun pourcentage officiel suffisamment probant n'est enregistré.</p></div>;return <div className="progress-block"><div><span>{label}</span><b>{value}%</b></div><div className={`progress ${secondary?"secondary":""}`}><i style={{width:`${value}%`}}/></div></div>}

export function FatshimeterConsole(){
  const [filter,setFilter]=useState("Tous");const [selected,setSelected]=useState<(typeof projects)[number]|null>(null);const [proofProject,setProofProject]=useState<(typeof projects)[number]|null>(null);const [proofs,setProofs]=useState<Array<{project:string;ref:string;note:string;date:string}>>([]);
  const sectors=["Tous",...Array.from(new Set(projects.map(p=>p.sector)))];const visible=useMemo(()=>filter==="Tous"?projects:projects.filter(p=>p.sector===filter),[filter]);
  return <><div className="fatshi-toolbar"><div className="segmented">{sectors.map(sector=><button type="button" key={sector} className={filter===sector?"active":""} onClick={()=>setFilter(sector)}>{sector}</button>)}</div><ExportMenu title="Fatshimétrie locale — projets publics" dataset="state_projects" fileName="fatshimetrie-kasa-vubu" scopeLabel={filter==="Tous"?"tous les secteurs":`secteur : ${filter}`} rows={visible.map((p)=>({reference:p.id,projet:p.name,secteur:p.sector,statut:p.status,financement:p.funding,budget_cdf:p.budgetCdf??"",avancement_physique:p.physical??"",avancement_financier:p.financial??"",verification:p.verificationScope,preuve:p.evidence,date_preuve:p.evidenceDate,source:p.sourceLabel,url:p.sourceUrl}))} columns={[{key:"reference",label:"Référence"},{key:"projet",label:"Projet"},{key:"secteur",label:"Secteur"},{key:"statut",label:"Statut"},{key:"financement",label:"Financement"},{key:"budget_cdf",label:"Budget CDF"},{key:"avancement_physique",label:"Avancement physique %"},{key:"avancement_financier",label:"Avancement financier %"},{key:"verification",label:"Portée vérification"},{key:"preuve",label:"Preuve"},{key:"date_preuve",label:"Date preuve"},{key:"source",label:"Source"},{key:"url",label:"URL"}]} /></div><div className="project-grid">{visible.map(project=><article className="project-card" key={project.id}><div className="project-card-head"><span className="status info">{project.status}</span><span className={`evidence-badge ${project.verified?"verified":"pending"}`}>{project.verified?"Source identifiée":"À vérifier"}</span></div><small>{project.id} • {project.funding}</small><h3>{project.name}</h3><p>{project.sector} • Budget connu : {formatCdf(project.budgetCdf)}</p><ProgressLine label="Avancement physique" value={project.physical}/><ProgressLine label="Exécution financière" value={project.financial} secondary/><div className="evidence-line"><span>Portée de la vérification</span><strong>{project.verificationScope}</strong></div><div className="evidence-line"><span>Preuve enregistrée</span><strong>{project.evidence}</strong></div><div className="source-line"><span>{project.evidenceDate}</span><a href={project.sourceUrl} target="_blank" rel="noreferrer">{project.sourceLabel} ↗</a></div><div className="card-actions"><button type="button" onClick={()=>setSelected(project)}>Voir la fiche</button><button type="button" onClick={()=>setProofProject(project)}>Ajouter une preuve</button></div></article>)}</div><div className="inline-warning"><strong>Principe de prudence :</strong> une source peut confirmer qu'un projet est programmé ou qu'un chantier existe sans permettre d'afficher un pourcentage d'avancement. e‑Commune laisse ces indicateurs vides tant qu'une preuve datée et mesurable n'est pas enregistrée.</div>
  {selected&&<Modal title={selected.name} close={()=>setSelected(null)}><div className="detail-grid"><div><small>Référence</small><b>{selected.id}</b></div><div><small>Secteur</small><b>{selected.sector}</b></div><div><small>Financement</small><b>{selected.funding}</b></div><div><small>Budget connu</small><b>{formatCdf(selected.budgetCdf)}</b></div></div><div className="registry-item"><strong>Preuve source</strong><span>{selected.evidence}</span></div><div className="registry-item"><strong>Preuves ajoutées dans la session</strong><span>{proofs.filter(p=>p.project===selected.id).length}</span></div></Modal>}
  {proofProject&&<Modal title={`Ajouter une preuve — ${proofProject.id}`} close={()=>setProofProject(null)}><form className="form-grid" onSubmit={(e)=>{e.preventDefault();const fd=new FormData(e.currentTarget);setProofs(v=>[...v,{project:proofProject.id,ref:String(fd.get("ref")),note:String(fd.get("note")),date:String(fd.get("date"))}]);setProofProject(null)}}><label>Date de la preuve<input name="date" type="date" required/></label><label>Référence / URL<input name="ref" required/></label><label className="span-2">Observation<textarea name="note" rows={4} required/></label><div className="span-2 modal-actions"><button type="button" onClick={()=>setProofProject(null)}>Annuler</button><button className="primary-btn">Enregistrer la preuve</button></div></form></Modal>}
  </>}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){return <div className="modal-backdrop" onClick={close}><div className="modal-card" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><small>Fatshimétrie locale</small><h3>{title}</h3></div><button type="button" className="icon-btn" onClick={close}>×</button></div>{children}</div></div>}
