"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { ExportMenu } from "./ExportMenu";

type Stall = { id:string; market:string; code:string; zone:string; category:string; occupant:string; phone:string; activity:string; start:string; end:string; feeRef:string; status:"OCCUPE"|"LIBRE"|"SUSPENDU"; payment:"A_JOUR"|"A_PAYER"|"RETARD"; lastInspection:string; note:string };

export function MarketStallsConsole({ canWrite }: { canWrite:boolean }) {
  const [rows,setRows]=useState<Stall[]>([]); const [open,setOpen]=useState(false); const [selected,setSelected]=useState<Stall|null>(null); const [query,setQuery]=useState(""); const [scope,setScope]=useState("Tous"); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState("");

  async function refresh(){setLoading(true);setError("");try{const response=await fetch("/api/markets/stalls",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Registre indisponible.");setRows(data.rows||[]);}catch(e){setError(e instanceof Error?e.message:"Chargement impossible.");}finally{setLoading(false);}}
  useEffect(()=>{void refresh();},[]);

  const filtered=useMemo(()=>rows.filter((r)=>(scope==="Tous"||r.status===scope)&&`${r.code} ${r.market} ${r.occupant} ${r.activity}`.toLowerCase().includes(query.toLowerCase())),[rows,query,scope]);
  const due=rows.filter((r)=>r.payment!=="A_JOUR").length;

  async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const fd=new FormData(event.currentTarget);const response=await fetch("/api/markets/stalls",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({market:fd.get("market"),code:fd.get("code"),zone:fd.get("zone"),category:fd.get("category"),occupant:fd.get("occupant"),phone:fd.get("phone"),activity:fd.get("activity"),start:fd.get("start"),end:fd.get("end"),feeRef:fd.get("feeRef"),note:fd.get("note")})});const data=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(data.error||"Étalage non enregistré.");return;}setRows(v=>[data.row,...v]);setOpen(false);event.currentTarget.reset();}

  async function patch(stall:Stall,changes:Partial<Stall>){setBusy(true);setError("");const response=await fetch(`/api/markets/stalls/${stall.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:changes.status,payment:changes.payment,note:changes.note})});const data=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(data.error||"Mise à jour impossible.");return;}setRows(v=>v.map(r=>r.id===stall.id?{...r,...changes}:r));setSelected(s=>s&&s.id===stall.id?{...s,...changes}:s);}

  async function inspect(stall:Stall){setBusy(true);setError("");const response=await fetch(`/api/markets/stalls/${stall.id}/inspections`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({result:"Contrôle de routine",observations:"Contrôle enregistré depuis le tableau de bord e-Commune."})});const data=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(data.error||"Inspection non enregistrée.");return;}const date=new Date().toISOString().slice(0,10);setRows(v=>v.map(r=>r.id===stall.id?{...r,lastInspection:date}:r));setSelected(s=>s&&s.id===stall.id?{...s,lastInspection:date}:s);}

  function collect(stall:Stall){ try{localStorage.setItem("ecommune.collection-prefill",JSON.stringify({taxpayer:stall.occupant,taxpayerRef:stall.code,taxCode:stall.feeRef}));}catch{} window.location.href="/recettes";}
  return <div className="module-stack">
    {error&&<div className="inline-warning"><strong>PostgreSQL :</strong> {error}</div>}
    <div className="metrics-grid compact"><Mini label="Étalages enregistrés" value={String(rows.length)} note="base PostgreSQL"/><Mini label="Occupés" value={String(rows.filter(r=>r.status==="OCCUPE").length)} note="actifs"/><Mini label="Paiements à suivre" value={String(due)} note="à payer / retard"/><Mini label="Marchés" value={String(new Set(rows.map(r=>r.market)).size)} note="référencés"/></div>
    <section className="panel"><div className="panel-head"><div><h2>Registre des étalages</h2><p>Identification, occupation, échéance, référence fiscale et contrôle terrain</p></div><div className="toolbar-actions"><ExportMenu title="Registre des marchés et étalages" dataset="market_stalls" fileName="etalages-kasa-vubu" scopeLabel={scope!=="Tous"||query?`filtre statut=${scope}; recherche=${query||"—"}`:"registre complet"} rows={filtered.map((r)=>({marche:r.market,code:r.code,zone:r.zone,categorie:r.category,occupant:r.occupant,telephone:r.phone,activite:r.activity,debut:r.start,fin:r.end,reference_fiscale:r.feeRef,statut:r.status,paiement:r.payment,derniere_inspection:r.lastInspection,note:r.note}))} columns={[{key:"marche",label:"Marché"},{key:"code",label:"Code"},{key:"zone",label:"Zone"},{key:"categorie",label:"Catégorie"},{key:"occupant",label:"Occupant"},{key:"telephone",label:"Téléphone"},{key:"activite",label:"Activité"},{key:"debut",label:"Début"},{key:"fin",label:"Fin / renouvellement"},{key:"reference_fiscale",label:"Référence fiscale"},{key:"statut",label:"Statut"},{key:"paiement",label:"Paiement"},{key:"derniere_inspection",label:"Dernière inspection"},{key:"note",label:"Note"}]} />{canWrite&&<button className="primary-btn" type="button" onClick={()=>setOpen(true)}>+ Enregistrer un étalage</button>}</div></div>
      <div className="table-toolbar"><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Code, occupant, activité, marché…"/><select value={scope} onChange={(e)=>setScope(e.target.value)}><option>Tous</option><option value="OCCUPE">Occupés</option><option value="LIBRE">Libres</option><option value="SUSPENDU">Suspendus</option></select><span className="data-badge officiel">{loading?"Chargement…":`${filtered.length} résultat(s)`}</span></div>
      <div className="table-wrap"><table><thead><tr><th>Code</th><th>Marché / zone</th><th>Occupant</th><th>Activité</th><th>Échéance</th><th>Paiement</th><th>Statut</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><b>{r.code}</b><br/><small>{r.category}</small></td><td>{r.market}<br/><small>Zone {r.zone||"—"}</small></td><td>{r.occupant||"Libre"}<br/><small>{r.phone||"—"}</small></td><td>{r.activity}</td><td>{r.end||"—"}</td><td><span className={`status ${r.payment==="A_JOUR"?"success":r.payment==="RETARD"?"danger":"info"}`}>{r.payment==="A_JOUR"?"À jour":r.payment==="RETARD"?"Retard":"À payer"}</span></td><td><span className={`status ${r.status==="OCCUPE"?"success":""}`}>{r.status}</span></td><td><button type="button" onClick={()=>setSelected(r)}>Suivre</button></td></tr>)}</tbody></table></div>
      {!loading&&!rows.length&&<div className="empty-state compact"><strong>Aucun étalage enregistré</strong><p>Le premier enregistrement sera conservé dans PostgreSQL et attribué à l'agent connecté.</p></div>}
    </section>
    {open&&<Modal title="Nouvel étalage" close={()=>setOpen(false)}><form className="form-grid" onSubmit={add}><label>Marché<input name="market" defaultValue="Marché Gambela" required/></label><label>Code étalage<input name="code" placeholder="GAM-A-001" required/></label><label>Zone<input name="zone"/></label><label>Catégorie<select name="category"><option>Étalage</option><option>Kiosque</option><option>Boutique</option><option>Dépôt</option><option>Emplacement temporaire</option></select></label><label>Occupant<input name="occupant" required/></label><label>Téléphone<input name="phone"/></label><label className="span-2">Activité<input name="activity" required/></label><label>Début d'occupation<input name="start" type="date" required/></label><label>Fin / renouvellement<input name="end" type="date"/></label><label>Référence fiscale<input name="feeRef" placeholder="Code du droit applicable"/></label><label>Note<input name="note"/></label><div className="span-2 modal-actions"><button type="button" onClick={()=>setOpen(false)}>Annuler</button><button className="primary-btn" disabled={busy}>{busy?"Enregistrement…":"Enregistrer"}</button></div></form></Modal>}
    {selected&&<Modal title={`Suivi ${selected.code}`} close={()=>setSelected(null)}><div className="detail-grid"><div><small>Marché</small><b>{selected.market}</b></div><div><small>Occupant</small><b>{selected.occupant}</b></div><div><small>Activité</small><b>{selected.activity}</b></div><div><small>Référence fiscale</small><b>{selected.feeRef||"À renseigner"}</b></div></div><div className="workflow-actions"><button type="button" onClick={()=>collect(selected)}>Percevoir / ouvrir Recettes</button><button type="button" disabled={busy||!canWrite} onClick={()=>void patch(selected,{payment:"A_JOUR"})}>Marquer paiement à jour</button><button type="button" disabled={busy||!canWrite} onClick={()=>void patch(selected,{payment:"RETARD"})}>Signaler retard</button><button type="button" disabled={busy||!canWrite} onClick={()=>void inspect(selected)}>Enregistrer contrôle du jour</button><button type="button" disabled={busy||!canWrite} onClick={()=>void patch(selected,{status:selected.status==="SUSPENDU"?"OCCUPE":"SUSPENDU"})}>{selected.status==="SUSPENDU"?"Réactiver":"Suspendre"}</button></div><div className="registry-item"><strong>Dernière inspection</strong><span>{selected.lastInspection||"Aucune inspection enregistrée"}</span></div></Modal>}
  </div>;
}
function Mini({label,value,note}:{label:string;value:string;note:string}){return <article className="metric-card"><div className="metric-head"><span>{label}</span></div><strong className="metric-value">{value}</strong><span className="metric-meta">{note}</span></article>}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){return <div className="modal-backdrop" onClick={close}><div className="modal-card" onClick={(e)=>e.stopPropagation()}><div className="modal-head"><div><small>e‑Commune Kasa‑Vubu</small><h3>{title}</h3></div><button className="icon-btn" type="button" onClick={close}>×</button></div>{children}</div></div>}
