"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { ExportMenu } from "./ExportMenu";

type GeoFeature = { type?: string; properties?: Record<string, unknown>; geometry?: { type?: string; coordinates?: unknown } | null };
type FeatureCollection = { type?: string; features?: GeoFeature[] };
type Parcel = { id:string; reference:string; quartier:string; avenue:string; usage:string; occupant:string; ownerClaim:string; area:number; source:string; status:"A_VALIDER"|"VALIDEE"|"LITIGE"; points:Array<{lat:number;lon:number}>; createdAt:string };

export function ParcelImportConsole({ canWrite }: { canWrite: boolean }) {
  const [fileName, setFileName] = useState(""); const [payload, setPayload] = useState<FeatureCollection | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [loading,setLoading]=useState(true); const [mode,setMode]=useState<"import"|"digitize">("digitize"); const [parcels,setParcels]=useState<Parcel[]>([]); const [points,setPoints]=useState<Array<{lat:number;lon:number}>>([]); const [query,setQuery]=useState("");

  async function refresh(){setLoading(true);try{const response=await fetch("/api/parcels",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Registre parcellaire indisponible.");setParcels(data.rows||[]);}catch(e){setMessage(e instanceof Error?e.message:"Chargement impossible.");}finally{setLoading(false);}}
  useEffect(()=>{void refresh();},[]);

  const stats = useMemo(() => { const features = payload?.features || []; const geometryTypes = Array.from(new Set(features.map((feature) => feature.geometry?.type).filter(Boolean))); const withReference = features.filter((feature) => feature.properties?.reference || feature.properties?.id || feature.properties?.numero).length; return { count: features.length, geometryTypes, withReference }; }, [payload]);
  const filtered=parcels.filter(p=>`${p.reference} ${p.quartier} ${p.avenue} ${p.occupant}`.toLowerCase().includes(query.toLowerCase()));

  async function readFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setFileName(file.name); setMessage(""); try { const parsed = JSON.parse(await file.text()) as FeatureCollection; if (parsed.type !== "FeatureCollection" || !Array.isArray(parsed.features)) throw new Error("Le fichier doit être un GeoJSON FeatureCollection."); setPayload(parsed); } catch (error) { setPayload(null); setMessage(error instanceof Error ? error.message : "Fichier GeoJSON invalide."); } }
  async function validateImport() { if (!payload || !canWrite) return; setBusy(true); setMessage(""); const response = await fetch("/api/parcels/import", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sourceReference: fileName, geojson: payload }) }); const data = await response.json().catch(() => ({})); setMessage(data.message || data.error || "Import terminé."); setBusy(false); if(response.ok){setPayload(null);setFileName("");await refresh();} }

  function addPoint(){const prev=points[points.length-1];setPoints(v=>[...v,{lat:prev?Number((prev.lat+0.00015).toFixed(6)):-4.3429,lon:prev?Number((prev.lon+0.00015).toFixed(6)):15.3002}]);}
  function updatePoint(index:number,field:"lat"|"lon",value:string){setPoints(v=>v.map((p,i)=>i===index?{...p,[field]:Number(value)}:p));}
  async function saveParcel(event:FormEvent<HTMLFormElement>){event.preventDefault();if(points.length<3){setMessage("Ajoutez au moins 3 sommets pour former une parcelle.");return;}setBusy(true);setMessage("");const fd=new FormData(event.currentTarget);const response=await fetch("/api/parcels",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reference:fd.get("reference"),quartier:fd.get("quartier"),avenue:fd.get("avenue"),usage:fd.get("usage"),occupant:fd.get("occupant"),ownerClaim:fd.get("ownerClaim"),area:Number(fd.get("area")||0),source:fd.get("source"),points})});const data=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setMessage(data.error||"Parcelle non enregistrée.");return;}setParcels(v=>[data.row,...v]);setPoints([]);setMessage(`Parcelle ${data.row.reference} enregistrée en PostgreSQL comme donnée à valider.`);event.currentTarget.reset();}
  function exportGeoJson(){const fc={type:"FeatureCollection",features:parcels.map(p=>({type:"Feature",properties:{reference:p.reference,quartier:p.quartier,avenue:p.avenue,usage:p.usage,occupant:p.occupant,owner_claim:p.ownerClaim,area_m2:p.area,source:p.source,status:p.status},geometry:{type:"Polygon",coordinates:[[...p.points.map(pt=>[pt.lon,pt.lat]),...(p.points.length?[[p.points[0].lon,p.points[0].lat]]:[])] ]}}))};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(fc,null,2)],{type:"application/geo+json"}));a.download="parcelles-kasa-vubu.geojson";a.click();URL.revokeObjectURL(a.href);}

  return <div className="parcel-console module-stack">
    <div className="segmented module-tabs"><button type="button" className={mode==="digitize"?"active":""} onClick={()=>setMode("digitize")}>Numériser une parcelle</button><button type="button" className={mode==="import"?"active":""} onClick={()=>setMode("import")}>Importer GeoJSON</button></div>
    {mode==="digitize"&&<section className="panel"><div className="panel-head"><div><h2>Numérisation parcellaire assistée</h2><p>Créer la fiche, saisir les sommets GPS et conserver la provenance documentaire dans PostgreSQL.</p></div><span className="data-badge a_valider">AUCUNE PREUVE DE PROPRIÉTÉ CRÉÉE</span></div>
      <form className="form-grid" onSubmit={saveParcel}><label>Référence parcelle<input name="reference" required placeholder="KSV-PAR-0001"/></label><label>Quartier<select name="quartier" required><option>Anciens Combattants</option><option>Assossa</option><option>Katanga</option><option>Lubumbashi</option><option>Lodja</option><option>O.N.L.</option><option>Salongo</option></select></label><label>Avenue<input name="avenue" required/></label><label>Usage<select name="usage"><option>Résidentiel</option><option>Commercial</option><option>Administratif</option><option>Équipement public</option><option>Mixte</option><option>Autre</option></select></label><label>Occupant / demandeur<input name="occupant"/></label><label>Propriétaire déclaré<input name="ownerClaim" placeholder="Déclaration non probante"/></label><label>Superficie déclarée (m²)<input name="area" type="number" min="0" step="0.01"/></label><label>Source / pièce<input name="source" required placeholder="Plan, fiche cadastrale, PV terrain…"/></label>
        <div className="span-2 coordinate-editor"><div className="panel-head"><div><h3>Sommets GPS</h3><p>Au moins 3 points. Les coordonnées sont modifiables avant enregistrement.</p></div><button type="button" onClick={addPoint}>+ Ajouter un sommet</button></div>{points.length===0?<div className="empty-state compact"><strong>Aucun sommet</strong><p>Ajoutez les points relevés sur terrain ou saisis depuis un plan géoréférencé.</p></div>:<div className="coordinate-list">{points.map((p,i)=><div key={i}><b>P{i+1}</b><label>Lat<input type="number" step="0.000001" value={p.lat} onChange={e=>updatePoint(i,"lat",e.target.value)}/></label><label>Lon<input type="number" step="0.000001" value={p.lon} onChange={e=>updatePoint(i,"lon",e.target.value)}/></label><button type="button" onClick={()=>setPoints(v=>v.filter((_,x)=>x!==i))}>×</button></div>)}</div>}</div>
        <div className="span-2 modal-actions"><button type="button" onClick={()=>setPoints([])}>Effacer la géométrie</button><button className="primary-btn" disabled={!canWrite||busy}>{busy?"Enregistrement…":"Enregistrer la parcelle à valider"}</button></div>
      </form>{message&&<div className="inline-warning parcel-message">{message}</div>}
    </section>}

    {mode==="import"&&<section className="panel parcel-import-panel"><div className="panel-head"><div><h2>Importer un référentiel parcellaire</h2><p>GeoJSON provenant d'une source administrative identifiée</p></div><span className={`data-badge ${canWrite ? "officiel" : "a_valider"}`}>{canWrite ? "IMPORT AUTORISÉ" : "LECTURE SEULE"}</span></div><div className="parcel-dropzone"><input id="parcel-file" type="file" accept=".geojson,.json,application/geo+json,application/json" onChange={readFile} disabled={!canWrite}/><label htmlFor="parcel-file"><strong>{fileName || "Choisir un fichier GeoJSON"}</strong><span>Polygones/multipolygones • maximum 5 000 entités par import pilote</span></label></div>{payload&&<div className="parcel-preview-metrics"><div><span>Entités</span><strong>{stats.count}</strong></div><div><span>Avec référence</span><strong>{stats.withReference}</strong></div><div><span>Géométries</span><strong>{stats.geometryTypes.join(", ") || "—"}</strong></div></div>}<button className="primary-btn" type="button" disabled={!payload||!canWrite||busy} onClick={validateImport}>{busy?"Import…":"Importer dans PostgreSQL"}</button>{message&&<div className="inline-warning parcel-message">{message}</div>}</section>}

    <section className="panel"><div className="panel-head"><div><h2>Registre parcellaire</h2><p>Références persistées en base, avec statut administratif séparé de la géométrie.</p></div><div className="toolbar-actions"><ExportMenu title="Registre parcellaire" dataset="parcels" fileName="parcelles-kasa-vubu" scopeLabel={query?`filtre : ${query}`:"registre complet"} rows={filtered.map((p)=>({reference:p.reference,quartier:p.quartier,avenue:p.avenue,usage:p.usage,occupant:p.occupant,proprietaire_declare:p.ownerClaim,superficie_m2:p.area,source:p.source,statut:p.status,nombre_sommets:p.points.length,date_creation:p.createdAt}))} columns={[{key:"reference",label:"Référence"},{key:"quartier",label:"Quartier"},{key:"avenue",label:"Avenue"},{key:"usage",label:"Usage"},{key:"occupant",label:"Occupant"},{key:"proprietaire_declare",label:"Propriétaire déclaré"},{key:"superficie_m2",label:"Superficie m²"},{key:"source",label:"Source"},{key:"statut",label:"Statut"},{key:"nombre_sommets",label:"Sommets GPS"},{key:"date_creation",label:"Date création"}]} /><button type="button" onClick={exportGeoJson} disabled={!parcels.length}>GeoJSON</button></div></div><div className="table-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Référence, quartier, avenue, occupant…"/><span className="data-badge officiel">{loading?"Chargement…":`${filtered.length} parcelle(s)`}</span></div>{!loading&&filtered.length===0?<div className="empty-state parcel-empty"><strong>0 parcelle enregistrée</strong><p>Numérisez une parcelle ou importez un référentiel documenté.</p></div>:<div className="table-wrap"><table><thead><tr><th>Référence</th><th>Localisation</th><th>Usage</th><th>Occupant</th><th>Géométrie</th><th>Source</th><th>Statut</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><b>{p.reference}</b></td><td>{p.quartier}<br/><small>{p.avenue}</small></td><td>{p.usage}</td><td>{p.occupant||"—"}</td><td>{p.points.length} sommets<br/><small>{p.area?`${p.area} m² déclarés`:"surface à calculer"}</small></td><td>{p.source}</td><td><span className={`status ${p.status==="VALIDEE"?"success":p.status==="LITIGE"?"danger":"info"}`}>{p.status==="A_VALIDER"?"À valider":p.status}</span></td></tr>)}</tbody></table></div>}</section>
  </div>;
}
