export type DataValidation = "OFFICIEL" | "SECTORIEL" | "REFERENTIEL_OUVERT" | "A_VALIDER";
export type AssetCategory = "ADMINISTRATION" | "SANTE" | "EDUCATION" | "MARCHE" | "CULTURE";

export type TerritorialAsset = {
  id: string;
  name: string;
  category: AssetCategory;
  subtype: string;
  quartier?: string;
  address?: string;
  lat?: number;
  lon?: number;
  validation: DataValidation;
  sourceLabel: string;
  sourceUrl?: string;
  note?: string;
};

// Référentiel viaire pilote dérivé du graphe OpenStreetMap pour Kasa-Vubu.
// Il doit être rapproché du registre viaire communal avant usage administratif opposable.
export const kasaVubuStreets: Record<string, string[]> = {
  "Anciens Combattants": [
    "Avenue des Sports",
    "Avenue Gambela",
    "Avenue Kasa-Vubu",
    "Rue Befale",
    "Rue Bomboma",
    "Rue Busu-Melo",
    "Rue Djolu",
    "Rue Gemena",
    "Rue Ikelemba",
    "Rue Irebu",
    "Rue Lopori",
  ],
  Assossa: ["Avenue de la Force Publique", "Rue Sandoa"],
  Katanga: [
    "Avenue Busu-Djanoa",
    "Avenue Lisala",
    "Avenue Maringa",
    "Avenue Shaba",
    "Rond-point Kimpwanza",
    "Rue Bomboma",
    "Rue Bongandanga",
    "Rue Bosobolo",
    "Rue Eala",
    "Rue Gemena",
  ],
  Lodja: [
    "Avenue Kasa-Vubu",
    "Avenue Lokalama",
    "Enseignement",
    "Luozi",
    "Mpozo",
    "Rue Kanda-Kanda",
    "Rue Lodja",
    "Rue Mangai",
    "Rue Masi-Manimba",
    "Rue Oshwe",
    "Rue Popo Kabaka",
    "Rue Tshikapa",
  ],
  Lubumbashi: [
    "Avenue de la Force Publique",
    "Avenue Gambela",
    "Avenue Kasa-Vubu",
    "Avenue Lukandu",
    "Avenue Opala",
    "Avenue Shaba",
    "Place du 17 Mai",
    "Rue Banalia",
    "Rue Faradje",
    "Rue Momboyo",
    "Rue Sandoa",
    "Rue Yahuma",
  ],
  "O.N.L.": [
    "Avenue Assossa",
    "Avenue Birmanie",
    "Avenue de Zomfi",
    "Avenue des Sports",
    "Avenue Dialele",
    "Avenue Saio",
    "Rue de Binanga",
    "Rue de Bombo",
    "Rue de Dembo",
    "Rue de Kasangulu",
    "Rue de Kibambi",
    "Rue de Kiduma",
    "Rue de Kimbola",
    "Rue de Kimpemba",
    "Rue de Kimwenza",
    "Rue de Kimwisi",
    "Rue de Kinanga",
    "Rue de Kindongolosi",
    "Rue de Kintanu",
    "Rue de Kinzwana",
    "Rue de Kipaku",
    "Rue de Kipaku bis",
    "Rue de Kivuka",
    "Rue de Lemfu",
    "Rue de Mbonda",
    "Rue de Selo",
    "Rue de Yongo",
  ],
  Salongo: [
    "Avenue Assossa",
    "Avenue de la Victoire",
    "Avenue Gambela",
    "Enseignement",
    "Luozi",
    "Rond-point Kimpwanza",
    "Rue de Kanda-kanda",
    "Rue Dibaya",
    "Rue Inzia",
    "Triomphal",
  ],
};

export const territorialAssets: TerritorialAsset[] = [
  {
    id: "ADM-KSV-001",
    name: "Maison communale de Kasa-Vubu",
    category: "ADMINISTRATION",
    subtype: "Hôtel de ville / maison communale",
    address: "Avenue des Sports, Kasa-Vubu",
    lat: -4.34229,
    lon: 15.30247,
    validation: "OFFICIEL",
    sourceLabel: "Portail officiel communal + référentiel OpenStreetMap",
    sourceUrl: "https://www.kasa-vubu.cd/contact/",
  },
  {
    id: "SAN-KSV-000",
    name: "Hôpital du Cinquantenaire",
    category: "SANTE",
    subtype: "Hôpital",
    address: "Avenue Pierre Mulele / ex-24 Novembre",
    lat: -4.34191,
    lon: 15.29631,
    validation: "SECTORIEL",
    sourceLabel: "Ministère de la Santé + OpenStreetMap/Wikidata",
    sourceUrl: "https://sante.gouv.cd/hopitaux",
  },
  {
    id: "EDU-KSV-001",
    name: "Lycée Motema Mpiko",
    category: "EDUCATION",
    subtype: "École / lycée",
    address: "Avenue Assossa",
    lat: -4.34559,
    lon: 15.30153,
    validation: "REFERENTIEL_OUVERT",
    sourceLabel: "OpenStreetMap / Mapcarta",
  },
  {
    id: "EDU-KSV-002",
    name: "Lycée 2 et 3 Kasa-Vubu",
    category: "EDUCATION",
    subtype: "École / lycée",
    lat: -4.34458,
    lon: 15.30016,
    validation: "REFERENTIEL_OUVERT",
    sourceLabel: "OpenStreetMap / Mapcarta",
  },
  {
    id: "EDU-KSV-003",
    name: "Université Catholique Cardinal Malula",
    category: "EDUCATION",
    subtype: "Université",
    lat: -4.33964,
    lon: 15.29911,
    validation: "REFERENTIEL_OUVERT",
    sourceLabel: "OpenStreetMap / Mapcarta",
  },
  {
    id: "EDU-KSV-004",
    name: "Athénée de la Victoire",
    category: "EDUCATION",
    subtype: "École",
    address: "Rue de Kasangulu",
    validation: "REFERENTIEL_OUVERT",
    sourceLabel: "OpenStreetMap / OpenAlfa — référentiel éducation",
    sourceUrl: "https://dr-congo-streets.openalfa.com/kasa-vubu/education",
  },
  {
    id: "EDU-KSV-005",
    name: "Complexe Scolaire KANDA",
    category: "EDUCATION",
    subtype: "École",
    address: "Avenue des Sports",
    validation: "REFERENTIEL_OUVERT",
    sourceLabel: "OpenStreetMap / OpenAlfa — référentiel éducation",
    sourceUrl: "https://dr-congo-streets.openalfa.com/kasa-vubu/education",
  },
  {
    id: "EDU-KSV-006",
    name: "École Armée du Salut",
    category: "EDUCATION",
    subtype: "École",
    address: "Rue Faradje",
    validation: "REFERENTIEL_OUVERT",
    sourceLabel: "OpenStreetMap / OpenAlfa — référentiel éducation",
    sourceUrl: "https://dr-congo-streets.openalfa.com/kasa-vubu/education",
  },
  {
    id: "EDU-KSV-007",
    name: "Lycée Madame de Sévigné",
    category: "EDUCATION",
    subtype: "Lycée",
    address: "Avenue de l'Enseignement",
    validation: "REFERENTIEL_OUVERT",
    sourceLabel: "OpenStreetMap / OpenAlfa — référentiel éducation",
    sourceUrl: "https://dr-congo-streets.openalfa.com/kasa-vubu/education",
  },
  {
    id: "EDU-KSV-008",
    name: "Lycée Toyokana",
    category: "EDUCATION",
    subtype: "Lycée",
    address: "113, Avenue Lisala",
    validation: "REFERENTIEL_OUVERT",
    sourceLabel: "OpenStreetMap / OpenAlfa — référentiel éducation",
    sourceUrl: "https://dr-congo-streets.openalfa.com/kasa-vubu/education",
  },
  {
    id: "EDU-KSV-009",
    name: "Institut national pilote d’enseignement des sciences de santé",
    category: "EDUCATION",
    subtype: "Institut supérieur / sciences de santé",
    address: "Boulevard Triomphal, Kasa-Vubu",
    validation: "REFERENTIEL_OUVERT",
    sourceLabel: "OpenStreetMap / OpenAlfa — référentiel éducation",
    sourceUrl: "https://dr-congo-streets.openalfa.com/kasa-vubu/education",
  },
  {
    id: "CUL-KSV-001",
    name: "Bibliothèque Miezi",
    category: "CULTURE",
    subtype: "Bibliothèque",
    address: "103, Avenue Sport",
    lat: -4.3412,
    lon: 15.29958,
    validation: "REFERENTIEL_OUVERT",
    sourceLabel: "OpenStreetMap / Mapcarta",
  },
  {
    id: "CUL-KSV-002",
    name: "Carrefour des Jeunes",
    category: "CULTURE",
    subtype: "Centre des arts / jeunesse",
    address: "Avenue Kasa-Vubu",
    validation: "REFERENTIEL_OUVERT",
    sourceLabel: "OpenStreetMap / OpenAlfa",
    sourceUrl: "https://rues-rd-congo.openalfa.com/rues/rue-masi-manimba-kasa-vubu-kinshasa-republique-democratique-du-congo",
  },
  {
    id: "MAR-KSV-001",
    name: "Marché Gambela",
    category: "MARCHE",
    subtype: "Marché public / populaire",
    address: "Avenue Gambela",
    lat: -4.33583,
    lon: 15.31028,
    validation: "REFERENTIEL_OUVERT",
    sourceLabel: "Référentiel géographique ouvert et documentation publique",
    note: "À rapprocher du registre communal des marchés avant usage administratif.",
  },
];

export const territorySources = [
  {
    label: "Portail officiel de la commune de Kasa-Vubu",
    kind: "OFFICIEL",
    usage: "quartiers, administration, adresse, population et informations communales",
    url: "https://www.kasa-vubu.cd/",
  },
  {
    label: "OpenStreetMap — relation 388094",
    kind: "REFERENTIEL_OUVERT",
    usage: "limite communale, rues, géolocalisation et équipements",
    url: "https://www.openstreetmap.org/relation/388094",
  },
  {
    label: "Référentiel de rues OpenStreetMap / OpenAlfa",
    kind: "REFERENTIEL_OUVERT",
    usage: "liste pilote des voies par quartier",
    url: "https://dr-congo-streets.openalfa.com/kasa-vubu",
  },
  {
    label: "Ministère de la Santé publique",
    kind: "SECTORIEL",
    usage: "référencement d'établissements sanitaires majeurs",
    url: "https://sante.gouv.cd/hopitaux",
  },
] as const;

export const totalPilotStreets = Object.values(kasaVubuStreets).reduce((sum, streets) => sum + streets.length, 0);
